In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
## Sentences 
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
     'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
## Defining the vocabulary size
voc_size = 10000

In [7]:
## OHE Representation
one_hot_repr = [one_hot(words,voc_size) for words in sent]
one_hot_repr

[[9102, 2325, 7669, 8195],
 [9102, 2325, 7669, 8359],
 [9102, 248, 7669, 7723],
 [4532, 2217, 2684, 5328, 5878],
 [4532, 2217, 2684, 5328, 4986],
 [7588, 9102, 8471, 7669, 6124],
 [5639, 4617, 484, 5328]]

In [8]:
## Word Embeddings Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_len = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_len)
print(embedded_docs)

[[   0    0    0    0 9102 2325 7669 8195]
 [   0    0    0    0 9102 2325 7669 8359]
 [   0    0    0    0 9102  248 7669 7723]
 [   0    0    0 4532 2217 2684 5328 5878]
 [   0    0    0 4532 2217 2684 5328 4986]
 [   0    0    0 7588 9102 8471 7669 6124]
 [   0    0    0    0 5639 4617  484 5328]]


In [11]:
## Feature Represntation
dim = 10

In [12]:
model = Sequential()
model.add(Embedding(input_dim=voc_size, output_dim=10,input_length=sent_len))
model.compile('adam','mse')

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [14]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 279ms/step


array([[[-0.04084361,  0.01123514, -0.04071494, -0.03971431,
          0.04815933, -0.04711143, -0.02731227,  0.03750071,
         -0.04041426,  0.03616128],
        [-0.04084361,  0.01123514, -0.04071494, -0.03971431,
          0.04815933, -0.04711143, -0.02731227,  0.03750071,
         -0.04041426,  0.03616128],
        [-0.04084361,  0.01123514, -0.04071494, -0.03971431,
          0.04815933, -0.04711143, -0.02731227,  0.03750071,
         -0.04041426,  0.03616128],
        [-0.04084361,  0.01123514, -0.04071494, -0.03971431,
          0.04815933, -0.04711143, -0.02731227,  0.03750071,
         -0.04041426,  0.03616128],
        [ 0.03898757, -0.01635756,  0.00125958,  0.01447624,
         -0.01816551,  0.03834465, -0.01109578,  0.00690203,
          0.02375365,  0.02261888],
        [ 0.00243213,  0.04894066,  0.0198206 , -0.04874825,
          0.00835948,  0.03991541,  0.04735282,  0.04854958,
          0.0285365 , -0.03647415],
        [ 0.0349828 ,  0.0420733 ,  0.03547596, -0.0